import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import InfiniteScroll from 'react-infinite-scroll-component';
import axios from 'axios';
import { data } from '../data/data';

const COUNTRIES = [
  {
    area: 'amazon.com',
    name: 'USA',
    checked: true
  },
  {
    area: 'amazon.ca',
    name: 'Canada',
    checked: false
  },
  {
    area: 'amazon.com.br',
    name: 'Brazil',
    checked: false
  },
  {
    area: 'amazon.com.mx',
    name: 'Mexico',
    checked: false
  },
  {
    area: 'amazon.in',
    name: 'India',
    checked: false
  },
  {
    area: 'amazon.co.jp',
    name: 'Japan',
    checked: false
  },
  {
    area: 'amazon.sg',
    name: 'Singapore',
    checked: false
  },
  {
    area: 'amazon.com.au',
    name: 'Australia',
    checked: false
  },
  {
    area: 'amazon.co.uk',
    name: 'UK',
    checked: false
  },
  {
    area: 'amazon.de',
    name: 'Germany',
    checked: false
  },
  {
    area: 'amazon.it',
    name: 'Italia',
    checked: false
  },
  {
    area: 'amazon.fr',
    name: 'France',
    checked: false
  },
  {
    area: 'amazon.es',
    name: 'Spain',
    checked: false
  },
  {
    area: 'amazon.se',
    name: 'Sweden',
    checked: false
  },
  {
    area: 'amazon.tr',
    name: 'Turkey',
    checked: false
  },
  {
    area: 'amazon.nl',
    name: 'Netherlands',
    checked: false
  }
];

export default function Home() {
  const [inputSearch, setInputSearch] = useState('');
  const [listProduct, setListProduct] = useState(data);
  const [country, setCountry] = useState('amazon.com');
  const [nameCountry, setNameCountry] = useState('USA');
  const inputHandler = (e) => {
    let lowerCase = e.target.value.toLowerCase();
    setInputSearch(lowerCase);
  };

  const clearInput = (e) => {
    setInputSearch('');
  };

  const filterData = data.filter((item, index) => {
    if (inputSearch === '' && index) {
      return item;
    } else if (inputSearch !== '') {
      return item.name.toLowerCase().includes(inputSearch);
    }
  });
  const replaceArea = (string, area) => {
    return string.replace('amazon.com', area);
  };

  const fetchMoreData = () => {
    setListProduct(data.slice(0, listProduct.length + 10));
  };

  const handleChangeSelected = (e) => {
    const prevCountry = 'amazon.com';
    let index = e.nativeEvent.target.selectedIndex;
    const currentCountry = e.nativeEvent.target[index].text;
    setNameCountry(currentCountry);
    setCountry(e.target.value);
  };

  useEffect(() => {
    setListProduct(data.slice(0, 10));
  }, []);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [inputSearch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Best Product Trending</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='search-bar'>
        <div className='content-title'>
          <p>Please enter product code in the search box</p>
        </div>
        <div className='input-content'>
          <input
            className='input-search'
            type='text'
            placeholder='Enter code here, example: 3'
            onChange={inputHandler}
            value={inputSearch}
            autoFocus
          />
          {inputSearch && (
            <span className='clear-input' onClick={clearInput}>
              <svg
                xmlns='http://www.w3.org/2000/svg'
                className='h-5 w-5'
                viewBox='0 0 20 20'
                fill='currentColor'
                color='#afafaf'
              >
                <path
                  fillRule='evenodd'
                  d='M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z'
                  clipRule='evenodd'
                />
              </svg>
            </span>
          )}
          <div className='icon-search'>
            <svg xmlns='http://www.w3.org/2000/svg' fill='#aaa' width='18px' height='18px' viewBox='0 0 512 512'>
              <path d='M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z' />
            </svg>
          </div>
        </div>
      </div>
      <div className='container-list'>
        {inputSearch ? (
          <div className='product-list'>
            {filterData.reverse().map((item, index) => (
              <div className='product-item' key={index}>
                <img src={item.imglink} className='imglink' />
                <div className='product-text'>
                  {item.sameproduct && <h6 className='mt-5'>Similar products</h6>}
                  <p>
                    Product code: <span className='code'>{item.name}</span>
                  </p>
                  <h5 className='north-america'>GLOBAL</h5>
                  <a href={item.usalink} target='_blank' className='custom-button'>
                    View prices on Amazon
                  </a>
                  <h5 className='north-america'> SELECT YOUR COUNTRY</h5>
                  <div className='selected-country'>
                    <select
                      name=''
                      className='custom-selected'
                      value={country}
                      id='countries'
                      onChange={handleChangeSelected}
                    >
                      {COUNTRIES.map((item, index) => (
                        <option value={item.area} key={index}>
                          {item.name}
                        </option>
                      ))}
                    </select>
                  </div>
                  <a href={replaceArea(item.usalink, country)} target='_blank' className='custom-button'>
                    {nameCountry} - View Prices on Amazon
                  </a>
                </div>
              </div>
            ))}
            <div>{!filterData.length ? <p>No matching results. Please search again</p> : <p></p>}</div>
          </div>
        ) : (
          <div>
            <a
              href='https://www.amazon.com/tryprimefree?ref_=assoc_tag_ph_1524238741396&_encoding=UTF8&camp=1789&creative=9325&linkCode=pf4&tag=naturalhuta-20&linkId=69b69f38c59313489c69b260889d3f79'
              target='_blank'
              className='custom-button banner'
            >
              Try Amazon Prime 30-Day Free Trial
            </a>
            {
              <InfiniteScroll
                dataLength={listProduct.length}
                next={fetchMoreData}
                hasMore={listProduct.length == data.length ? false : true}
                loader={<div className='dashed-loading'></div>}
                className='product-list'
              >
                {listProduct.map((item, index) => (
                  <div className='product-item' key={index}>
                    <img src={item.imglink} className='imglink' />
                    <div className='product-text'>
                      {item.sameproduct && <h6 className='mt-5'>Similar products</h6>}
                      <p>
                        Product code: <span className='code'>{item.name}</span>
                      </p>
                      <h5 className='north-america'>GLOBAL</h5>
                      <a href={item.usalink} target='_blank' className='custom-button'>
                        View prices on Amazon
                      </a>
                      <h5 className='north-america'> SELECT YOUR COUNTRY</h5>
                      <div className='selected-country'>
                        <select
                          name=''
                          className='custom-selected'
                          value={country}
                          id='countries'
                          onChange={handleChangeSelected}
                        >
                          {COUNTRIES.map((item, index) => (
                            <option value={item.area} key={index}>
                              {item.name}
                            </option>
                          ))}
                        </select>
                      </div>
                      <a href={replaceArea(item.usalink, country)} target='_blank' className='custom-button'>
                        {nameCountry} - View Prices on Amazon
                      </a>
                    </div>
                  </div>
                ))}
              </InfiniteScroll>
            }
          </div>
        )}
      </div>
    </div>
  );
}
